### ISSUE TITLE
Uninitialized values in bp_receive cause crashing

### ISSUE THREAD

**Issue by BrianSipos** [msancheznet/pyion#5]
There is a local struct which is left mostly uninitialized at
https://github.com/msancheznet/pyion/blob/e4dad84f3a9a7f52d7de40f7666ae01cca7f3113/pyion/_bp.c#L399

If the call to `base_bp_receive_data()` and then `help_receive_data()` result in an timeout-interrupted receive activity, the early returns, for example in https://github.com/msancheznet/pyion/blob/e4dad84f3a9a7f52d7de40f7666ae01cca7f3113/pyion/base_bp.c#L134 will leave the members uninitialized and inconsistent. The members are only set around https://github.com/msancheznet/pyion/blob/e4dad84f3a9a7f52d7de40f7666ae01cca7f3113/pyion/base_bp.c#L172

A solution to this is to initialize all members around the struct allocation, not just the `payload` member as is currently.

**Comment by msancheznet** [comment]
Thanks for the feedback.

This issue is fixed in commit be43f000018ef21e8314eabf03bd2101014ceb99 for v4.1.0
